### PR TITLE
Add redirects for truecolours spellings

### PR DESCRIPTION
**Pull request by pmac**
For our friends in the UK and Canada this could be a popular spelling
for our domain should they hear about it. Let's support them.

### CODE REVIEW

**Comment by pmac** [comment]
@bkochendorfer I don't know if this is worth the trouble to setup the other new subdomain. It's not that big a deal. If not just let me know and i'll take that part of the PR out.

**Review by duallain — APPROVED** [review]
LGTM, since it's a subdomain I think it should be easy enough to add, it'll be worth the trouble.

**Comment by duallain** [comment]
@pmac should be merged and working now.

**Comment by pmac** [comment]
Thank you!

**Pull request merged**
