### PR TITLE
screenshots.firefox.com decommissioning SVCSE-449 SVCSE-741

### PR DESCRIPTION
**Pull request by jbuck**
## Refractr PR Checklist

JIRA ticket: [link to relevant JIRA or other system ticket]

When creating a PR for Refractr, confirm you've done the following steps for smooth CI and CD experiences:
- [ ] Is this the right place for your redirect (e.g. developer.mozilla.com/* redirects should be managed by MDN; other examples here as known)?
- [ ] Have you updated the relevant YAML in the PR?
- [ ] Have you checked the relevant YAML for any possible dupes regarding your domain?
- [ ] Have you checked if there are any TLS cert concerns - e.g. if the domain being redirected already exists, and it is being changed to point at Refractr, is a temporary TLS 'outage' while waiting for Lets Encrypt certification via HTTP challenge okay? If not, [have you followed these steps for using DNS challenges with our cert-manager setup](https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges)?
- [ ] If desired, have you generated the Nginx manually to confirm addition works as expected? 
- [ ] If desired, are you able to connect to EKS (cluster itse-apps-prod-1, namespace fluxcd) to more closely monitor the deploys?

After PR merge, next steps include:
- [ ] If going straight from main merge & Stage deploy to a release & production deploy, create the relevant GitHub release with an incremented version / tag applied.
- [ ] Confirm you are ready and able to perform the requested DNS creation or change post-deploy?

### CODE REVIEW

**Comment by jbuck** [comment]
So this is a start - what I could some assistance with is having some paths return HTTP 410 Gone instead of redirecting - specifically `/event`, `/timing`, and `/images`

**Comment by bkochendorfer** [comment]
@jbuck refractr doesn't really have the ability to do what you are asking but there is a workaround if `404` is acceptable instead of `410`. Take a look at what we do here for [ftv](https://github.com/mozilla-it/refractr/blob/34fa7fd67c6f9d5a914a3d1caad3af0c48f35acc/prod-refractr.yml#L1004). We only redirect particular URLs. You'd have to do the inverse of what you are asking, setup a redirect for the other URLS, leave those three and let them 404

**Comment by jbuck** [comment]
@bkochendorfer how terrible an idea is this take? 😅

**Comment by bkochendorfer** [comment]
Oh that should work just fine

**Review by bkochendorfer — APPROVED** [review]

**Pull request merged**
