### PR TITLE
change ideas.m.o redirect to https://mozilla.github.io/imo-placeholder/

### PR DESCRIPTION
**Pull request by cmharlow**
See https://jira.mozilla.com/browse/SE-1666

Checklist:

- [x] TLS cert request? - not needed here
- [x] DNS creation or change request? - not needed here
- [x] update prod.refractr.yaml
- [x] test locally generation of nginx config via dev.refractr.yaml
- [x] test locally the generated Docker image with above configurations
- [x] connected to EKS to watch release

### CODE REVIEW

**Comment by cmharlow** [comment]
I'm still not sure where the nginx configs get generated if I'm honest; I know its part of the Docker build according to the docs, but I just don't see where the command is called. I think its somehow inherent in the doit / dodo.py stuff.

**Comment by cmharlow** [comment]
yeah, has to be through `doit run publish` in travis which shows these steps in the run (but not in doit.py):

```
doit publish

.  creds

Unable to locate credentials. You can configure credentials by running aws configure.

.  login

.  deployed

.  version

.  schema

validating stage-refractr.yml against refractr/schema.yml => SUCCESS

.  ingress

bin/refractr ingress --ingress-template refractr/ingress.yaml.template > refractr/image/ingress.yaml

.  nginx

bin/refractr nginx > refractr/nginx/conf.d/refractr.conf

.  refracts

bin/refractr --output json show > refractr/image/refracts

Building refractr

.  build
```

And if I'm understanding this correctly, its actually building this image using docker-compose, not docker directly.

**Review by duallain — APPROVED** [review]
LGTM, and because we're already pointing the right hand dns to refractr, all we should have to do is promote this to prod.  It should not generate new certs, and 'just' deploy new versions of refractr with a different redirect.

```
ideas.mozilla.org.	3600	IN	CNAME	prod.refractr.mozit.cloud.
```

**Comment by duallain** [comment]
FWIW I believe the build happens through this entry point script.  You can see that the entrypoint in refractr/Dockerfile is this file - https://github.com/mozilla-it/refractr/blob/main/refractr/image/refractr.sh.  Though trying to read that back, it seems like there might be another layer of abstraction before we actually build the nginx config.  

This calls the render function, so I think that the flow is dockerfile -> refractr.sh ingress -> refract ingress ?  
 https://github.com/mozilla-it/refractr/blob/58c2bd9cbb701cceb83793352250f773e3746c40/bin/refractr#L205

**Review by sciurus — APPROVED** [review]

**Comment by cmharlow** [comment]
@duallain so i'm thinking that the nginx & kubernetes configuration generation (at least the nginx one) happens pre-docker build, for the following reasons:
1. there are no commands in the Dockerfile that run a generate step (afaict; there are very few RUN directives at all);
2. pulling a few shipped images down from ecr and poking around, I see the generated nginx & k8s files in the image already (going around the entrypoint script, so nothing would be run beforehand by that entrypoint script i don't believe);
3. and I don't see where we copy over the originating *.refractr.yaml files into the image to be used for conversations within the image.

I think that means it has to be the doit steps in the build pipeline that run nginx & k8s generation then docker build, but i think I need to dig into doit more to understand where those steps are coming from (I just don't see that full doit run publish DAG defined in such a way that it'd include all the steps that do run).

**Pull request merged**
