### PR TITLE
Redirect testpilot.firefox.com to fpn.firefox.com

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
The tests are failing because TravisCI doesn't have the expected AWS credentials.
This is due to the PR coming from a fork, so it's expected.

Regardless of this PR, we should fix this, not failing on PRs coming from a fork.

**Review by The-smooth-operator — APPROVED** [review]
This looks good.
Thanks for submitting it and for following the alphabetic order placing the redirection

**Comment by jbuck** [comment]
@The-smooth-operator Could you merge this PR? I don't have write access :)

**Comment by jbuck** [comment]
Also, this can totally wait until January to merge/deploy, no rush

**Comment by The-smooth-operator** [comment]
I've noticed that all other redirections with a single source (like this one) are listed inline instead of using an array.
Please @jbuck would you mind doing a one liner? Like in `- krakenbenchmark.mozilla.org/: krakenbenchmark.mozilla.com`

We will get this deployed into production this week.

**Review by The-smooth-operator — CHANGES_REQUESTED** [review]
I've noticed that all other redirections with a single source (like this one) are listed inline instead of using an array.
Please @jbuck would you mind doing a one liner? Like in - krakenbenchmark.mozilla.org/: krakenbenchmark.mozilla.com

We will get this deployed into production this week.

**Comment by limed** [comment]
@jbuck do you mind rebasing against main to get the commit a4f8b1a6aa0fe969fdabef1b8ac9353876651f64

**Pull request closed without merging**
