### PR TITLE
repair www.mozillians.org lack of cert / bad CNAME

### PR DESCRIPTION
**Pull request by cmharlow**
## Refractr PR Checklist

JIRA ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1617378

When creating a PR for Refractr, confirm you've done the following steps for smooth CI and CD experiences:
- [x] Have you updated the relevant YAML in the PR?
- [x] Have you checked if there are any TLS cert concerns - e.g. if the domain being redirected already exists, and it is being changed to point at Refractr, is a temporary TLS 'outage' while waiting for Lets Encrypt certification via HTTP challenge okay? If not, [have you followed these steps for using DNS challenges with our cert-manager setup](https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges)?
- [x] If desired, have you generated the Nginx manually to confirm addition works as expected? 
- [x] If desired, are you able to connect to EKS (cluster itse-apps-prod-1, namespace fluxcd) to more closely monitor the deploys?

After PR merge, next steps include:
- [x] If going straight from main merge & Stage deploy to a release & production deploy, create the relevant GitHub release with an incremented version / tag applied.
- [x] Confirm you are ready and able to perform the requested DNS creation or change post-deploy?

### CODE REVIEW

**Comment by cmharlow** [comment]
Cleaning up infoblox as well, given www CNAME was left behind pointing at mozillians.org which doesn't do anything to generate cert via refractr.

**Comment by cmharlow** [comment]
never mind, this dns isn't in infoblox, its a rando cname in partsys / partinfra route53. repairing there.

**Review by duallain — APPROVED** [review]
I'm very curious about if this pr is enough to get everything working.  I am fairly sure (80% or so) that the current weird setup with the cname would work if we were to merge/promote this pr without any other changes, as it does take an extra hop, but eventually gets to refractr correctly.


(just so I don't forget - current dns)
```
dig www.mozillians.org +short
mozillians.org.
44.235.246.155
44.236.48.31
44.236.72.93
```

**Comment by cmharlow** [comment]
@duallain dns work already done, trying to get this patterned as possible since refractr dns is spread everyone and used to be any kind of format that the person writing it had (or thought they had) working.

**Pull request merged**
